version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/src/app
    networks:
      - buzzstack

networks:
  buzzstack:
